ALTER TABLE session ADD INDEX session_index(value);
ALTER TABLE category ADD INDEX category_index(category_id);
ALTER TABLE category_group ADD INDEX category_group_index(group_id);
ALTER TABLE file ADD INDEX file_index(file_id);
ALTER TABLE group_info ADD INDEX group_info_index(group_id);
ALTER TABLE group_member ADD INDEX group_member_index(user_id, is_primary);
ALTER TABLE record ADD INDEX record_index(record_id, created_by, category_id, application_group, status);
ALTER TABLE record_comment ADD INDEX record_comment_index(linked_record_id);
ALTER TABLE record_item_file ADD INDEX record_item_file_index(linked_record_id);
ALTER TABLE record_last_access ADD INDEX record_last_access_index(user_id, record_id);
ALTER TABLE user ADD INDEX user_index(user_id);
